name       : paperwork-shell
version    : 2.0.3
release    : 2
source     :
    - https://pypi.io/packages/source/p/paperwork-shell/paperwork-shell-2.0.3.tar.gz : 17db4b0dd827710d8a5c4190ea425933912c83306bdfb4c499056a5302b483f5
homepage   : https://openpaper.work/
license    : GPL-3.0-or-later
component  : programming.python
summary    : Paperwork's shell interface
description: |
    Paperwork is a GUI to make papers searchable. paperwork-cli is an interactive shell frontend for Paperwork. paperwork-json is a non-interactive frontend for Paperwork that always return JSON results.
builddeps  :
    - paperwork-backend
    - python-fabulous
    - python-getkey
    - python-psutil
rundeps    :
    - paperwork-backend
    - python-fabulous
    - python-getkey
setup      : |
    %patch < $pkgfiles/00001-missing-version.patch paperwork-shell/src/paperwork_shell/_version.py
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test
