name       : paperwork-shell
version    : 2.1.0
release    : 3
source     :
    - https://pypi.io/packages/source/p/paperwork-shell/paperwork-shell-2.1.0.tar.gz : 3da7753da77b9538e33eadfcd4cc065fa1c582fe9345a72fa62e8b9fcd973ff4
homepage   : https://openpaper.work/
license    : GPL-3.0-or-later
component  : programming.python
summary    : Paperwork's shell interface
description: |
    Paperwork is a GUI to make papers searchable. paperwork-cli is an interactive shell frontend for Paperwork. paperwork-json is a non-interactive frontend for Paperwork that always return JSON results.
builddeps  :
    - paperwork-backend
    - python-fabulous
rundeps    :
    - paperwork-backend
    - python-fabulous
build      : |
    %python3_setup
install    : |
    %python3_install
